### ISSUE TITLE
Constraints on events df to sel can't be strings

### ISSUE THREAD

**Issue by teibit** [teibit/xarray-events#1]
[This test](https://github.com/teibit/xarray-events/blob/2d7e6b124715a87a64460aec27ee8989f96a6de8/tests/test.py#L304) fails if we modify the selection to be `selection = {'event_type' = 'pass'}` because `isinstance('pass', Collection)` evaluates to `True`.

**Comment by hsharrison** [comment]
I guess it makes sense that string is a collection since it supports the `in` operator.

In this case the fix is probably as simple as `if isinstance(value, Collection)  and not isinstance(value, str)`.

**Comment by teibit** [comment]
That fixed it. Thanks!
